package POJO;
// Generated 08-21-2019 04:10:44 PM by Hibernate Tools 4.3.1



/**
 * Danos generated by hbm2java
 */
public class Danos  implements java.io.Serializable {


     private DanosId id;
     private Factura factura;
     private Mueble mueble;
     private Float subtotal;

    public Danos() {
    }

	
    public Danos(DanosId id, Factura factura, Mueble mueble) {
        this.id = id;
        this.factura = factura;
        this.mueble = mueble;
    }
    public Danos(DanosId id, Factura factura, Mueble mueble, Float subtotal) {
       this.id = id;
       this.factura = factura;
       this.mueble = mueble;
       this.subtotal = subtotal;
    }
   
    public DanosId getId() {
        return this.id;
    }
    
    public void setId(DanosId id) {
        this.id = id;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Mueble getMueble() {
        return this.mueble;
    }
    
    public void setMueble(Mueble mueble) {
        this.mueble = mueble;
    }
    public Float getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Float subtotal) {
        this.subtotal = subtotal;
    }




}


