package POJO;
// Generated 08-21-2019 04:10:44 PM by Hibernate Tools 4.3.1



/**
 * EventoServicios generated by hbm2java
 */
public class EventoServicios  implements java.io.Serializable {


     private EventoServiciosId id;
     private Evento evento;
     private Servicio servicio;
     private Float subtotal;

    public EventoServicios() {
    }

	
    public EventoServicios(EventoServiciosId id, Evento evento, Servicio servicio) {
        this.id = id;
        this.evento = evento;
        this.servicio = servicio;
    }
    public EventoServicios(EventoServiciosId id, Evento evento, Servicio servicio, Float subtotal) {
       this.id = id;
       this.evento = evento;
       this.servicio = servicio;
       this.subtotal = subtotal;
    }
   
    public EventoServiciosId getId() {
        return this.id;
    }
    
    public void setId(EventoServiciosId id) {
        this.id = id;
    }
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }
    public Float getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Float subtotal) {
        this.subtotal = subtotal;
    }




}


