package POJO;
// Generated 08-11-2019 01:00:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Habitacion generated by hbm2java
 */
public class Habitacion  implements java.io.Serializable {


     private int idHab;
     private String numeroHab;
     private String tipoHab;
     private String descripcionHab;
     private Integer capacidadHab;
     private Float precioHab;
     private String estadoHab;
     private Set serviciosContratadoses = new HashSet(0);
     private Set muebles = new HashSet(0);
     private Set reservacionHabitacioneses = new HashSet(0);

    public Habitacion() {
    }

	
    public Habitacion(int idHab, String numeroHab, String tipoHab) {
        this.idHab = idHab;
        this.numeroHab = numeroHab;
        this.tipoHab = tipoHab;
    }
    public Habitacion(int idHab, String numeroHab, String tipoHab, String descripcionHab, Integer capacidadHab, Float precioHab, String estadoHab, Set serviciosContratadoses, Set muebles, Set reservacionHabitacioneses) {
       this.idHab = idHab;
       this.numeroHab = numeroHab;
       this.tipoHab = tipoHab;
       this.descripcionHab = descripcionHab;
       this.capacidadHab = capacidadHab;
       this.precioHab = precioHab;
       this.estadoHab = estadoHab;
       this.serviciosContratadoses = serviciosContratadoses;
       this.muebles = muebles;
       this.reservacionHabitacioneses = reservacionHabitacioneses;
    }
   
    public int getIdHab() {
        return this.idHab;
    }
    
    public void setIdHab(int idHab) {
        this.idHab = idHab;
    }
    public String getNumeroHab() {
        return this.numeroHab;
    }
    
    public void setNumeroHab(String numeroHab) {
        this.numeroHab = numeroHab;
    }
    public String getTipoHab() {
        return this.tipoHab;
    }
    
    public void setTipoHab(String tipoHab) {
        this.tipoHab = tipoHab;
    }
    public String getDescripcionHab() {
        return this.descripcionHab;
    }
    
    public void setDescripcionHab(String descripcionHab) {
        this.descripcionHab = descripcionHab;
    }
    public Integer getCapacidadHab() {
        return this.capacidadHab;
    }
    
    public void setCapacidadHab(Integer capacidadHab) {
        this.capacidadHab = capacidadHab;
    }
    public Float getPrecioHab() {
        return this.precioHab;
    }
    
    public void setPrecioHab(Float precioHab) {
        this.precioHab = precioHab;
    }
    public String getEstadoHab() {
        return this.estadoHab;
    }
    
    public void setEstadoHab(String estadoHab) {
        this.estadoHab = estadoHab;
    }
    public Set getServiciosContratadoses() {
        return this.serviciosContratadoses;
    }
    
    public void setServiciosContratadoses(Set serviciosContratadoses) {
        this.serviciosContratadoses = serviciosContratadoses;
    }
    public Set getMuebles() {
        return this.muebles;
    }
    
    public void setMuebles(Set muebles) {
        this.muebles = muebles;
    }
    public Set getReservacionHabitacioneses() {
        return this.reservacionHabitacioneses;
    }
    
    public void setReservacionHabitacioneses(Set reservacionHabitacioneses) {
        this.reservacionHabitacioneses = reservacionHabitacioneses;
    }




}


