package POJO;
// Generated 08-11-2019 01:00:59 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Insumo generated by hbm2java
 */
public class Insumo  implements java.io.Serializable {


     private int idInsumo;
     private String nombreInsumo;
     private String descripcion;
     private Integer cantidad;
     private Date fechaPedido;
     private Date fechaAPedir;
     private Date cantidadAPedir;

    public Insumo() {
    }

	
    public Insumo(int idInsumo, String nombreInsumo, Date fechaPedido, Date fechaAPedir, Date cantidadAPedir) {
        this.idInsumo = idInsumo;
        this.nombreInsumo = nombreInsumo;
        this.fechaPedido = fechaPedido;
        this.fechaAPedir = fechaAPedir;
        this.cantidadAPedir = cantidadAPedir;
    }
    public Insumo(int idInsumo, String nombreInsumo, String descripcion, Integer cantidad, Date fechaPedido, Date fechaAPedir, Date cantidadAPedir) {
       this.idInsumo = idInsumo;
       this.nombreInsumo = nombreInsumo;
       this.descripcion = descripcion;
       this.cantidad = cantidad;
       this.fechaPedido = fechaPedido;
       this.fechaAPedir = fechaAPedir;
       this.cantidadAPedir = cantidadAPedir;
    }
   
    public int getIdInsumo() {
        return this.idInsumo;
    }
    
    public void setIdInsumo(int idInsumo) {
        this.idInsumo = idInsumo;
    }
    public String getNombreInsumo() {
        return this.nombreInsumo;
    }
    
    public void setNombreInsumo(String nombreInsumo) {
        this.nombreInsumo = nombreInsumo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFechaPedido() {
        return this.fechaPedido;
    }
    
    public void setFechaPedido(Date fechaPedido) {
        this.fechaPedido = fechaPedido;
    }
    public Date getFechaAPedir() {
        return this.fechaAPedir;
    }
    
    public void setFechaAPedir(Date fechaAPedir) {
        this.fechaAPedir = fechaAPedir;
    }
    public Date getCantidadAPedir() {
        return this.cantidadAPedir;
    }
    
    public void setCantidadAPedir(Date cantidadAPedir) {
        this.cantidadAPedir = cantidadAPedir;
    }




}


