package POJO;
// Generated 08-01-2019 03:43:22 PM by Hibernate Tools 4.3.1



/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer idPro;
     private String rucPro;
     private String nombrePro;
     private String direccionPro;
     private String telefonoEmp;
     private String emailEmp;

    public Proveedor() {
    }

	
    public Proveedor(String rucPro, String nombrePro) {
        this.rucPro = rucPro;
        this.nombrePro = nombrePro;
    }
    public Proveedor(String rucPro, String nombrePro, String direccionPro, String telefonoEmp, String emailEmp) {
       this.rucPro = rucPro;
       this.nombrePro = nombrePro;
       this.direccionPro = direccionPro;
       this.telefonoEmp = telefonoEmp;
       this.emailEmp = emailEmp;
    }
   
    public Integer getIdPro() {
        return this.idPro;
    }
    
    public void setIdPro(Integer idPro) {
        this.idPro = idPro;
    }
    public String getRucPro() {
        return this.rucPro;
    }
    
    public void setRucPro(String rucPro) {
        this.rucPro = rucPro;
    }
    public String getNombrePro() {
        return this.nombrePro;
    }
    
    public void setNombrePro(String nombrePro) {
        this.nombrePro = nombrePro;
    }
    public String getDireccionPro() {
        return this.direccionPro;
    }
    
    public void setDireccionPro(String direccionPro) {
        this.direccionPro = direccionPro;
    }
    public String getTelefonoEmp() {
        return this.telefonoEmp;
    }
    
    public void setTelefonoEmp(String telefonoEmp) {
        this.telefonoEmp = telefonoEmp;
    }
    public String getEmailEmp() {
        return this.emailEmp;
    }
    
    public void setEmailEmp(String emailEmp) {
        this.emailEmp = emailEmp;
    }




}


