package POJO;
// Generated 08-11-2019 01:00:59 AM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUser;
     private Empleado empleado;
     private String usernameUser;
     private String passwordUser;
     private String estadoUser;

    public Usuario() {
    }

	
    public Usuario(int idUser, Empleado empleado, String usernameUser, String passwordUser) {
        this.idUser = idUser;
        this.empleado = empleado;
        this.usernameUser = usernameUser;
        this.passwordUser = passwordUser;
    }
    public Usuario(int idUser, Empleado empleado, String usernameUser, String passwordUser, String estadoUser) {
       this.idUser = idUser;
       this.empleado = empleado;
       this.usernameUser = usernameUser;
       this.passwordUser = passwordUser;
       this.estadoUser = estadoUser;
    }
   
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getUsernameUser() {
        return this.usernameUser;
    }
    
    public void setUsernameUser(String usernameUser) {
        this.usernameUser = usernameUser;
    }
    public String getPasswordUser() {
        return this.passwordUser;
    }
    
    public void setPasswordUser(String passwordUser) {
        this.passwordUser = passwordUser;
    }
    public String getEstadoUser() {
        return this.estadoUser;
    }
    
    public void setEstadoUser(String estadoUser) {
        this.estadoUser = estadoUser;
    }




}


