package POJO;
// Generated 07-30-2019 10:53:13 PM by Hibernate Tools 4.3.1



/**
 * ServiciosContratadosId generated by hbm2java
 */
public class ServiciosContratadosId  implements java.io.Serializable {


     private String numFact;
     private int idSer;

    public ServiciosContratadosId() {
    }

    public ServiciosContratadosId(String numFact, int idSer) {
       this.numFact = numFact;
       this.idSer = idSer;
    }
   
    public String getNumFact() {
        return this.numFact;
    }
    
    public void setNumFact(String numFact) {
        this.numFact = numFact;
    }
    public int getIdSer() {
        return this.idSer;
    }
    
    public void setIdSer(int idSer) {
        this.idSer = idSer;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ServiciosContratadosId) ) return false;
		 ServiciosContratadosId castOther = ( ServiciosContratadosId ) other; 
         
		 return ( (this.getNumFact()==castOther.getNumFact()) || ( this.getNumFact()!=null && castOther.getNumFact()!=null && this.getNumFact().equals(castOther.getNumFact()) ) )
 && (this.getIdSer()==castOther.getIdSer());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNumFact() == null ? 0 : this.getNumFact().hashCode() );
         result = 37 * result + this.getIdSer();
         return result;
   }   


}


