package POJO;
// Generated 08-07-2019 11:38:14 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer idEmp;
     private String cedulaEm;
     private String prinombreEmp;
     private String segnombreEmp;
     private String priapellidoEmp;
     private String segapellidoEmp;
     private String fotoEmp;
     private Date nacimientoEmp;
     private String telefonoEmp;
     private String emailEmp;
     private String cargoEmp;
     private Float sueldoEmp;
     private String estadoEmp;
     private Set usuarios = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(String cedulaEm, String prinombreEmp, String priapellidoEmp, String fotoEmp, Date nacimientoEmp, String telefonoEmp, String emailEmp, String cargoEmp) {
        this.cedulaEm = cedulaEm;
        this.prinombreEmp = prinombreEmp;
        this.priapellidoEmp = priapellidoEmp;
        this.fotoEmp = fotoEmp;
        this.nacimientoEmp = nacimientoEmp;
        this.telefonoEmp = telefonoEmp;
        this.emailEmp = emailEmp;
        this.cargoEmp = cargoEmp;
    }
    public Empleado(String cedulaEm, String prinombreEmp, String segnombreEmp, String priapellidoEmp, String segapellidoEmp, String fotoEmp, Date nacimientoEmp, String telefonoEmp, String emailEmp, String cargoEmp, Float sueldoEmp, String estadoEmp, Set usuarios) {
       this.cedulaEm = cedulaEm;
       this.prinombreEmp = prinombreEmp;
       this.segnombreEmp = segnombreEmp;
       this.priapellidoEmp = priapellidoEmp;
       this.segapellidoEmp = segapellidoEmp;
       this.fotoEmp = fotoEmp;
       this.nacimientoEmp = nacimientoEmp;
       this.telefonoEmp = telefonoEmp;
       this.emailEmp = emailEmp;
       this.cargoEmp = cargoEmp;
       this.sueldoEmp = sueldoEmp;
       this.estadoEmp = estadoEmp;
       this.usuarios = usuarios;
    }
   
    public Integer getIdEmp() {
        return this.idEmp;
    }
    
    public void setIdEmp(Integer idEmp) {
        this.idEmp = idEmp;
    }
    public String getCedulaEm() {
        return this.cedulaEm;
    }
    
    public void setCedulaEm(String cedulaEm) {
        this.cedulaEm = cedulaEm;
    }
    public String getPrinombreEmp() {
        return this.prinombreEmp;
    }
    
    public void setPrinombreEmp(String prinombreEmp) {
        this.prinombreEmp = prinombreEmp;
    }
    public String getSegnombreEmp() {
        return this.segnombreEmp;
    }
    
    public void setSegnombreEmp(String segnombreEmp) {
        this.segnombreEmp = segnombreEmp;
    }
    public String getPriapellidoEmp() {
        return this.priapellidoEmp;
    }
    
    public void setPriapellidoEmp(String priapellidoEmp) {
        this.priapellidoEmp = priapellidoEmp;
    }
    public String getSegapellidoEmp() {
        return this.segapellidoEmp;
    }
    
    public void setSegapellidoEmp(String segapellidoEmp) {
        this.segapellidoEmp = segapellidoEmp;
    }
    public String getFotoEmp() {
        return this.fotoEmp;
    }
    
    public void setFotoEmp(String fotoEmp) {
        this.fotoEmp = fotoEmp;
    }
    public Date getNacimientoEmp() {
        return this.nacimientoEmp;
    }
    
    public void setNacimientoEmp(Date nacimientoEmp) {
        this.nacimientoEmp = nacimientoEmp;
    }
    public String getTelefonoEmp() {
        return this.telefonoEmp;
    }
    
    public void setTelefonoEmp(String telefonoEmp) {
        this.telefonoEmp = telefonoEmp;
    }
    public String getEmailEmp() {
        return this.emailEmp;
    }
    
    public void setEmailEmp(String emailEmp) {
        this.emailEmp = emailEmp;
    }
    public String getCargoEmp() {
        return this.cargoEmp;
    }
    
    public void setCargoEmp(String cargoEmp) {
        this.cargoEmp = cargoEmp;
    }
    public Float getSueldoEmp() {
        return this.sueldoEmp;
    }
    
    public void setSueldoEmp(Float sueldoEmp) {
        this.sueldoEmp = sueldoEmp;
    }
    public String getEstadoEmp() {
        return this.estadoEmp;
    }
    
    public void setEstadoEmp(String estadoEmp) {
        this.estadoEmp = estadoEmp;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


