package POJO;
// Generated 08-07-2019 11:38:14 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Mueble generated by hbm2java
 */
public class Mueble  implements java.io.Serializable {


     private int idMue;
     private Habitacion habitacion;
     private String nombreMue;
     private String descripcionMue;
     private float precioMue;
     private Set danoses = new HashSet(0);

    public Mueble() {
    }

	
    public Mueble(int idMue, Habitacion habitacion, float precioMue) {
        this.idMue = idMue;
        this.habitacion = habitacion;
        this.precioMue = precioMue;
    }
    public Mueble(int idMue, Habitacion habitacion, String nombreMue, String descripcionMue, float precioMue, Set danoses) {
       this.idMue = idMue;
       this.habitacion = habitacion;
       this.nombreMue = nombreMue;
       this.descripcionMue = descripcionMue;
       this.precioMue = precioMue;
       this.danoses = danoses;
    }
   
    public int getIdMue() {
        return this.idMue;
    }
    
    public void setIdMue(int idMue) {
        this.idMue = idMue;
    }
    public Habitacion getHabitacion() {
        return this.habitacion;
    }
    
    public void setHabitacion(Habitacion habitacion) {
        this.habitacion = habitacion;
    }
    public String getNombreMue() {
        return this.nombreMue;
    }
    
    public void setNombreMue(String nombreMue) {
        this.nombreMue = nombreMue;
    }
    public String getDescripcionMue() {
        return this.descripcionMue;
    }
    
    public void setDescripcionMue(String descripcionMue) {
        this.descripcionMue = descripcionMue;
    }
    public float getPrecioMue() {
        return this.precioMue;
    }
    
    public void setPrecioMue(float precioMue) {
        this.precioMue = precioMue;
    }
    public Set getDanoses() {
        return this.danoses;
    }
    
    public void setDanoses(Set danoses) {
        this.danoses = danoses;
    }




}


